# Generated by Django 4.2.1 on 2023-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='contact',
            field=models.TextField(),
        ),
    ]
